"""empty message

Revision ID: 0a39563b24c1
Revises: 
Create Date: 2018-06-18 10:45:32.921885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a39563b24c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_message',
    sa.Column('m_id', sa.Integer(), nullable=False),
    sa.Column('m_gid', sa.Integer(), nullable=False),
    sa.Column('m_sell', sa.Integer(), nullable=False),
    sa.Column('m_content', sa.String(length=100), nullable=False),
    sa.Column('m_time', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('m_id')
    )
    op.add_column('t_order', sa.Column('o_name', sa.String(length=40), nullable=False))
    op.add_column('t_order', sa.Column('o_ordernumber', sa.String(length=50), nullable=False))
    op.alter_column('t_order', 'o_bid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('t_order', 'o_gid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('t_order', 'o_postcode',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('t_order', 'o_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('INDEX_oid', table_name='t_order')
    op.drop_index('t_order_ibfk_2', table_name='t_order')
    op.drop_constraint('t_order_fk_user', 't_order', type_='foreignkey')
    op.drop_constraint('t_order_ibfk_1', 't_order', type_='foreignkey')
    op.create_foreign_key(None, 't_order', 't_user', ['o_bid'], ['u_id'])
    op.create_foreign_key(None, 't_order', 't_goods', ['o_gid'], ['g_id'])
    op.drop_column('t_order', 'o_remark')
    op.drop_column('t_order', 'o_ordernum')
    op.drop_column('t_order', 'o_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_order', sa.Column('o_desc', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('t_order', sa.Column('o_ordernum', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('t_order', sa.Column('o_remark', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 't_order', type_='foreignkey')
    op.drop_constraint(None, 't_order', type_='foreignkey')
    op.create_foreign_key('t_order_ibfk_1', 't_order', 't_goods', ['o_gid'], ['g_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('t_order_fk_user', 't_order', 't_user', ['o_bid'], ['u_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('t_order_ibfk_2', 't_order', ['o_gid'], unique=False)
    op.create_index('INDEX_oid', 't_order', ['o_id'], unique=False)
    op.alter_column('t_order', 'o_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('t_order', 'o_postcode',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('t_order', 'o_gid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('t_order', 'o_bid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('t_order', 'o_ordernumber')
    op.drop_column('t_order', 'o_name')
    op.drop_table('t_message')
    # ### end Alembic commands ###
